version: '3.8'

services:
  server:
    build: .
    container_name: server
    restart: always
    volumes: #allows share data between the host machine and containers(- <host-path>:<container-path>), don't need to rebuild containers
      - ./:/usr/src/app
    ports: 
      - 5000:5000
    env_file: 
      - .env

  mongodb:
    image: mongo:4.0.2
    container_name: mongodb
    restart: always
    volumes:
      - ./.db/mongodata:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
